"""HEAD-only determinism check for the parity case matrix.

Runs each case generated by ``tests.check_main_parity.iter_cases`` twice
against the current checkout and compares the serialized result bytes.
This is deliberately separate from the main-vs-HEAD parity harness so it
can be used while another worker edits backend parity coverage.

Usage::

    python tests/check_head_determinism.py
    python tests/check_head_determinism.py --limit 100

Exit code: 0 if every repeated case is byte-identical, 1 otherwise.
"""
from __future__ import annotations

import argparse
import pickle
import sys
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tests.check_main_parity import iter_cases
from tests._main_parity_runner import run_one


def _result_bytes(result):
    """Stable byte signature for pickleable harness results."""
    return pickle.dumps(result, protocol=pickle.HIGHEST_PROTOCOL)


def _short_result(result):
    if result["status"] == "err":
        return (
            f"err {result.get('type', '<missing-type>')}: "
            f"{result.get('msg', '')!r}"
        )
    value = result.get("result")
    text = repr(value)
    if len(text) > 500:
        text = text[:497] + "..."
    return "ok " + text


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--limit", type=int, default=None,
        help="If set, only run the first N cases.",
    )
    parser.add_argument(
        "--show-passing", action="store_true",
        help="Print every deterministic case, not just mismatches.",
    )
    args = parser.parse_args(argv)

    cases = list(iter_cases())
    if args.limit is not None:
        cases = cases[: args.limit]

    print(f"Running {len(cases)} HEAD cases twice")
    mismatches = []
    for case_id, func, case_args, kwargs in cases:
        first = run_one(func, case_args, kwargs)
        second = run_one(func, case_args, kwargs)
        if _result_bytes(first) == _result_bytes(second):
            if args.show_passing:
                print(f"  OK   {case_id}")
            continue
        mismatches.append((case_id, first, second))

    print()
    print(
        f"Summary: {len(cases) - len(mismatches)} deterministic, "
        f"{len(mismatches)} nondeterministic, {len(cases)} total"
    )
    if mismatches:
        print()
        print("Nondeterministic cases:")
        for case_id, first, second in mismatches:
            print(f"  {case_id}")
            print(f"    first:  {_short_result(first)}")
            print(f"    second: {_short_result(second)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
